### ISSUE TITLE
Use a prism

### ISSUE THREAD

**Issue by tonymorris** [andrewthad/country#2]
Instead of the two functions `encodeNumeric` and `decodeNumeric` consider instead a value of the type `Prism' Country Word16`

The `prism'` construction function achieves this.

https://hackage.haskell.org/package/lens-4.15.1/docs/src/Control.Lens.Prism.html#prism%27

**Comment by andrewthad** [comment]
I'm totally open to adding encode/decode prisms. I wouldn't want to remove the existing encode/decode functions, since if you're not chaining optics together, prisms just make things more cumbersome. The way I sort of envision it is:

    encodeEnglish :: Country -> Text
    english :: Prism' Text Country
    decode :: Text -> Country -- decode is language-agnostic

Also, if you add this, I really like what Gabriel does is `pipes-parse` with the type aliases. Basically, he writes the `Prism'` type alias but doesn't export it, which gives everything a pleasant type signature.

**Comment by chessai** [comment]
closing this for similar reasons to #5
